### ISSUE TITLE
ultralytics class mismatch

### ISSUE THREAD

**Issue by ZeroAct** [snuailab/waffle_hub#139]
### Search before asking

- [X] I have searched the [issues](https://github.com///issues) and found no similar bug report.

### Bug

It occurs class mismatch error when one of the categories are not in actual annotations.

- example that 3 class has been registered.
```python
{
    "categories": [
        {
            "id": 1,
            "name": "wear",
            "supercategory": "Helmet"
        },
        {
            "id": 2,
            "name": "off",
            "supercategory": "Helmet"
        },
        {
            "id": 3,
            "name": "unknown",
            "supercategory": "Helmet"
        }
    ],
```

-> But dataset doesn't have the "unknown" annotation.

**Comment by dustjr1565** [comment]
If there is a category included in the categories list but it is not used in the data, would you like to remove it from the categories?

Could you please clarify what you mean by "class mismatch" and in what context or function it occurs?

**Comment by pmz-q** [comment]
> If there is a category included in the categories list but it is not used in the data, would you like to remove it from the categories?
> 
> Could you please clarify what you mean by "class mismatch" and in what context or function it occurs?

As-Is
- categories that aren't used for annotations are removed
To-Be
- categories should remain though they aren't used for annotations
