### ISSUE TITLE
When performing Ultralytics classification, there is a difference between the dataset's category and the hub's category order.

### ISSUE THREAD

**Issue by dustjr1565** [snuailab/waffle_hub#254]
### Search before asking

- [X] I have searched the [issues](https://github.com///issues) and found no similar bug report.

### Bug

category IDs may differ from the category names defined in the dataset.

category IDs are assigned sequentially based on the order of category names in ultralytics

**Comment by Jiyong-Jeon** [comment]
There doesn't seem to be any problem.
