### ISSUE TITLE
Windows copatibility issue (ultralytics)

### ISSUE THREAD

**Issue by ZeroAct** [snuailab/waffle_hub#34]
### Search before asking

- [X] I have searched the [issues](https://github.com///issues) and found no similar bug report.

### Bug

- cannot load pt file from linux on windows.

issue https://github.com/ultralytics/ultralytics/issues/1900

**Comment by ZeroAct** [comment]
@snuailab/deep-learning-team 
I'm not sure if this is our problem or not.
I'll fix it after they reply. 😂

**Comment by oneQuery** [comment]
> @snuailab/deep-learning-team I'm not sure if this is our problem or not. I'll fix it after they reply. 😂

@ZeroAct 
I am confident that using the Waffle on a Windows system will provide end customers with powerful accessibility, which should be one of our primary focus. 

By the way, Glenn has proposed a potential solution -> (https://github.com/ultralytics/ultralytics/issues/1900#issuecomment-1500783682).

**Comment by ZeroAct** [comment]
Yes, we should fix it.
I think he is not glenn.. I think that is chatgpt  or something 🤔
