### ISSUE TITLE
export models

### ISSUE THREAD

**Issue by ZeroAct** [snuailab/waffle_hub#5]
### Search before asking

- [X] I have searched the [issues](https://github.com///issues) and found no similar feature requests.

### Description

- Model could be exported in several formats like onnx, engine, etc.
- Input and output formats of exported models are
  - dependent on our convention (task specific).
  - independent with what model type is or backend is.

@snuailab/waffle 
Any Idea?

**Comment by ByteBrewer** [comment]
@ZeroAct  My rough thinking is, we need to disconnect the dependencies with tasks, model types, and backends based on the concepts of abstraction and generalization. Is it what you are asking?

**Comment by ZeroAct** [comment]
I meant that ultralytics detector and mmdet detector should have same input and output.
It means backend agnostic (independent).

But, detector and classifier should have different input and output.
It means task specific (dependent).

Is it clear?

**Comment by ByteBrewer** [comment]
Oh, I see. So, what you mean is that we are going to use the same in/out format for the same tasks regardless of the backends. Right? I agree.
