### ISSUE TITLE
When data don't exist, the progress value cannot reach 1.

### ISSUE THREAD

**Issue by dustjr1565** [snuailab/waffle_hub#58]
### Search before asking

- [X] I have searched the [issues](https://github.com///issues) and found no similar bug report.

### Bug

When data don't exist, the progress value cannot reach 1.

**Comment by ZeroAct** [comment]
Can you give me more information such as log?

**Comment by dustjr1565** [comment]
> Can you give me more information such as log?

The progress value of 1 can never be achieved in the inference callback when there are no images in the directory.
