### ISSUE TITLE
yolo export create the `labels/` folder into a wrong directory

### ISSUE THREAD

**Issue by oneQuery** [snuailab/waffle_hub#85]
### Search before asking

- [X] I have searched the [issues](https://github.com///issues) and found no similar bug report.

### Bug

When the image set directory has a multiple-depth heirarchy, the `label/` folder is generated in a wrong directory.
Right:
```
trian/
  ├- data1/
  │    ├- images/
  │    └- labels/
  └-  data2/
       ├- images/
       └- labels/
  ...
...
```
Wrong(I don't remember the bugged directory exactly. It was such like this):
```
train/
  ├- images/
  │   └- data1/
  └- labels/
      └- data1/
val/
...
```

**Comment by ZeroAct** [comment]
@dustjr1565 check this issue please~

**Comment by dustjr1565** [comment]
Could you please provide me with more details about the situation and what you are referring to?

I have confirmed that there were no issues when training with the current directory structure

**Comment by oneQuery** [comment]
@dustjr1565 You will easily reproduce the issue if you set up a small amount of dataset with multiple heirarchy. I noticed that issue during training the SafetyNet which has 700k dataset, so cannot show and reproduce exactly the same thing. I recommend you assuming you have multiple folders and multiple depth with really small dataset to reduce your working time. Or, you can just keep it until someone has a chance to convert the multi-hierarchy image folder structure, and then upload the issue as detail as possible. Up to you.
